In [49]:
import pandas as pd

In [50]:
from openpyxl import load_workbook

def get_sheetnames_xlsx(filepath):
    wb = load_workbook(filepath, read_only=True, keep_links=False)
    return wb.sheetnames

In [51]:
def preproc(df, arg):
    df = df.reset_index(names=["loc_2", "arg_1", "arg_2"])
    df = df[(df["loc_2"] != "합계") & (df["arg_1"] != "합계") & (df["arg_2"] != "선거인수")].copy()
    df["loc_1"] = arg

    df["18_29"] = df.loc[:, ["18세", "19세", "20-24세", "25-29세"]].sum(axis=1)
    df["30_39"] = df.loc[:, ["30-34세", "35-39세"]].sum(axis=1)
    df["40_49"] = df.loc[:, ["40-49세"]].sum(axis=1)
    df["50_59"] = df.loc[:, ["50-59세"]].sum(axis=1)
    df["60_"] = df.loc[:, ["60-69세", "70-79세", "80세이상"]].sum(axis=1)
    df = df.loc[:, ["loc_1", "loc_2", "arg_1", "18_29", "30_39", "40_49", "50_59", "60_"]]
    return df


mapping = {
    "강원": "강원도",
    "경기": "경기도",
    "경남": "경상남도",
    "경북": "경상북도",
    "광주": "광주광역시",
    "대구": "대구광역시",
    "대전": "대전광역시",
    "부산": "부산광역시",
    "서울": "서울특별시",
    "세종": "세종특별자치시",
    "울산": "울산광역시",
    "인천": "인천광역시",
    "전남": "전라남도",
    "전북": "전라북도",
    "제주": "제주특별자치도",
    "충남": "충청남도",
    "충북": "충청북도",
}

In [52]:
sheetnames = get_sheetnames_xlsx(
    "./../raw_data/제_8_전국동시지방선거_투표율/01_투표율분석결과(표본)/12.선거인의 성별·연령대별 분포(구시군별).xlsx"
)
sheetnames

['서울',
 '부산',
 '대구',
 '인천',
 '광주',
 '대전',
 '울산',
 '세종',
 '경기',
 '강원',
 '충북',
 '충남',
 '전북',
 '전남',
 '경북',
 '경남',
 '제주']

In [53]:
preproc_df_list = list()
for sheetname in sheetnames:
    raw_df = pd.read_excel(
        "./../raw_data/제_8_전국동시지방선거_투표율/01_투표율분석결과(표본)/12.선거인의 성별·연령대별 분포(구시군별).xlsx",
        sheet_name=sheetname,
        header=[3],
        index_col=[0, 1, 2],
    )
    df = raw_df.copy()
    preproc_df = preproc(df, sheetname)
    preproc_df_list.append(preproc_df)
전국동시지방선거_8_df = pd.concat(preproc_df_list, axis=0)
전국동시지방선거_8_df["loc_1"] = 전국동시지방선거_8_df["loc_1"].map(mapping)
전국동시지방선거_8_df

       loc_1 loc_2 arg_1  18_29  30_39  40_49  50_59   60_
9      서울특별시   종로구    남자    7.8    7.4    7.8    9.2  15.4
11     서울특별시   종로구    여자    8.2    7.8    8.5    9.3  18.8
15     서울특별시    중구    남자    8.0    9.1    8.1    9.2  14.7
17     서울특별시    중구    여자   10.0    9.0    7.4    8.1  16.5
21     서울특별시   용산구    남자    8.4    8.7    7.9    8.9  13.0
..       ...   ...   ...    ...    ...    ...    ...   ...
137     경상남도   합천군    여자    5.0    2.9    5.3    9.2  29.2
9    제주특별자치도   제주시    남자    9.4    7.7   10.2   10.7  12.3
11   제주특별자치도   제주시    여자    8.2    7.2   10.0    9.9  14.3
15   제주특별자치도  서귀포시    남자    6.7    5.5    9.1   11.9  16.9
17   제주특별자치도  서귀포시    여자    5.2    5.1    7.8   10.0  21.8

[496 rows x 8 columns]

In [54]:
전국동시지방선거_8_df.to_csv("./2nd_preproc_data/전국동시지방선거_투표율_8_df.csv")

In [55]:
sheetnames = get_sheetnames_xlsx(
    "./../raw_data/제_20_대통령선거_투표율/01_투표율분석결과(표본)/12.선거인의 성별·연령대별 분포(구시군별).xlsx"
)
sheetnames

['서울',
 '부산',
 '대구',
 '인천',
 '광주',
 '대전',
 '울산',
 '세종',
 '경기',
 '강원',
 '충북',
 '충남',
 '전북',
 '전남',
 '경북',
 '경남',
 '제주']

In [56]:
preproc_df_list = list()
for sheetname in sheetnames:
    raw_df = pd.read_excel(
        "./../raw_data/제_20_대통령선거_투표율/01_투표율분석결과(표본)/12.선거인의 성별·연령대별 분포(구시군별).xlsx",
        sheet_name=sheetname,
        header=[3],
        index_col=[0, 1, 2],
    )
    df = raw_df.copy()
    preproc_df = preproc(df, sheetname)
    preproc_df_list.append(preproc_df)
대통령선거_20_df = pd.concat(preproc_df_list, axis=0)
대통령선거_20_df["loc_1"] = 대통령선거_20_df["loc_1"].map(mapping)
대통령선거_20_df

       loc_1 loc_2 arg_1  18_29  30_39  40_49  50_59   60_
9      서울특별시   종로구    남자    9.8    6.6    7.4   10.5  14.1
11     서울특별시   종로구    여자   10.4    6.1    8.1   10.0  16.8
15     서울특별시    중구    남자    8.6    9.4    9.1    9.8  13.4
17     서울특별시    중구    여자    8.6   10.0    7.4    9.0  14.9
21     서울특별시   용산구    남자    9.1    9.1    9.7    8.8  10.9
..       ...   ...   ...    ...    ...    ...    ...   ...
137     경상남도   합천군    여자    4.0    3.1    5.8    8.5  29.8
9    제주특별자치도   제주시    남자    9.8    7.9   10.1   10.3  11.6
11   제주특별자치도   제주시    여자    9.2    7.8    9.9    9.8  13.9
15   제주특별자치도  서귀포시    남자    7.7    7.0   10.8    9.9  13.3
17   제주특별자치도  서귀포시    여자    7.0    7.8   10.0    9.6  16.9

[496 rows x 8 columns]

In [57]:
대통령선거_20_df.to_csv("./2nd_preproc_data/대통령선거_투표율_20_df.csv")

In [58]:
sheetnames = get_sheetnames_xlsx(
    "./../raw_data/제_21_국회의원선거_투표율/01_전체 선거인 표본조사/12.선거인의 성별·연령대별 분포(구시군별).xlsx"
)
sheetnames

['서울',
 '부산',
 '대구',
 '인천',
 '광주',
 '대전',
 '울산',
 '경기',
 '강원',
 '충북',
 '충남',
 '전북',
 '전남',
 '경북',
 '경남',
 '제주']

In [59]:
raw_df = pd.read_excel(
    "./../raw_data/제_21_국회의원선거_투표율/01_전체 선거인 표본조사/12.선거인의 성별·연령대별 분포(구시군별).xlsx",
    sheet_name=sheetname,
    header=[3],
    index_col=[0, 1, 2],
)

In [60]:
preproc_df_list = list()
for sheetname in sheetnames:
    raw_df = pd.read_excel(
        "./../raw_data/제_21_국회의원선거_투표율/01_전체 선거인 표본조사/12.선거인의 성별·연령대별 분포(구시군별).xlsx",
        sheet_name=sheetname,
        header=[2],
        index_col=[0, 1, 2],
    )
    df = raw_df.copy()
    preproc_df = preproc(df, sheetname)
    preproc_df_list.append(preproc_df)
국회의원선거_21_df = pd.concat(preproc_df_list, axis=0)
국회의원선거_21_df["loc_1"] = 국회의원선거_21_df["loc_1"].map(mapping)
국회의원선거_21_df

       loc_1 loc_2 arg_1  18_29  30_39  40_49  50_59   60_
9      서울특별시    중구    남자    9.3   10.3    8.0    8.8  12.2
11     서울특별시    중구    여자    9.1   11.1    8.3    9.2  13.7
15     서울특별시   용산구    남자    9.7    9.8    7.4    8.8  12.1
17     서울특별시   용산구    여자   10.1    9.4    8.1    9.4  15.1
21     서울특별시   성동구    남자   10.2    9.3    8.7    9.6  11.3
..       ...   ...   ...    ...    ...    ...    ...   ...
131     경상남도   합천군    여자    2.8    1.9    3.6    8.8  35.8
9    제주특별자치도   제주시    남자   10.1    7.4   10.3   10.5  11.0
11   제주특별자치도   제주시    여자    9.3    7.2   10.1   10.4  13.8
15   제주특별자치도  서귀포시    남자    7.8    8.9   10.8    9.8  12.3
17   제주특별자치도  서귀포시    여자    7.5    8.9    9.4    9.0  15.6

[464 rows x 8 columns]

In [61]:
국회의원선거_21_df.to_csv("./2nd_preproc_data/국회의원선거_투표율_21_df.csv")

In [62]:
국회의원선거_21_df["time"] = "2020_04"
대통령선거_20_df["time"] = "2022_03"
전국동시지방선거_8_df["time"] = "2022_06"

In [63]:
vote_rat_df = pd.concat([국회의원선거_21_df, 대통령선거_20_df, 전국동시지방선거_8_df], axis=0)
vote_rat_df

       loc_1 loc_2 arg_1  18_29  30_39  40_49  50_59   60_     time
9      서울특별시    중구    남자    9.3   10.3    8.0    8.8  12.2  2020_04
11     서울특별시    중구    여자    9.1   11.1    8.3    9.2  13.7  2020_04
15     서울특별시   용산구    남자    9.7    9.8    7.4    8.8  12.1  2020_04
17     서울특별시   용산구    여자   10.1    9.4    8.1    9.4  15.1  2020_04
21     서울특별시   성동구    남자   10.2    9.3    8.7    9.6  11.3  2020_04
..       ...   ...   ...    ...    ...    ...    ...   ...      ...
137     경상남도   합천군    여자    5.0    2.9    5.3    9.2  29.2  2022_06
9    제주특별자치도   제주시    남자    9.4    7.7   10.2   10.7  12.3  2022_06
11   제주특별자치도   제주시    여자    8.2    7.2   10.0    9.9  14.3  2022_06
15   제주특별자치도  서귀포시    남자    6.7    5.5    9.1   11.9  16.9  2022_06
17   제주특별자치도  서귀포시    여자    5.2    5.1    7.8   10.0  21.8  2022_06

[1456 rows x 9 columns]

In [64]:
vote_rat_df.to_csv("./2nd_preproc_data/vote_ratio_df.csv")